tailwindConfig: "./tailwind.config.js"
trailingComma: all
semi: false
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
embeddedLanguageFormatting: auto
singleAttributePerLine: true
